import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { requireAdmin } from "@/lib/auth/admin";
import { NextResponse } from "next/server";

/** Download the recording manifest CSV (generated by `pnpm content:packets`). */
export async function GET() {
  await requireAdmin();
  try {
    const csv = await readFile(resolve(process.cwd(), "content/recording-manifest.csv"), "utf8");
    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": 'attachment; filename="recording-manifest.csv"',
      },
    });
  } catch {
    return NextResponse.json(
      { error: "manifest_not_generated", hint: "run pnpm content:packets" },
      { status: 404 },
    );
  }
}
